name: 'Cabal Cache S3'
description: 'Cache Haskell packages to S3 to improve workflow execution time'
author: 'GitHub'
inputs:
  cabal-cache-download-uri:
    description: 'Location from which to download cabal-cache'
    default: https://github.com/haskell-works/cabal-cache/releases
  cabal-cache-version:
    description: 'Version of the cabal-cache'
    default: latest
  path:
    description: 'Path to the cabal project'
    required: true
  store-path:
    description: 'Path to the cabal-store'
    required: true
  dist-dir:
    description: 'The cabal dist directory'
    required: true
  region:
    description: 'AWS region of the S3 bucket'
    required: true
  archive-uri:
    description: 'Locations of the cabal-cache archives'
    required: true
  threads:
    description: 'Number of threads'
    required: true
  host-name:
    description: 'Hostname of the S3 provider'
    required: false
  host-port:
    description: 'Port of the S3 provider'
    required: false
  host-ssl:
    description: 'Whether to use SSL when querying the S3 provider'
    required: false
  enable-save:
    description: 'Whether to enable save'
    required: true
    default: true
  skip:
    description: 'Whether to skip this action'
    default: false
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: 'node16'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
